mongo:
  url: mongodb://localhost:27017/?authSource=admin
  initdb_database: "database"

r2:
  presign_expiration_sec: 400
  access_key: "access"
  secret_key: "secret"
  account_id: "account"
  bucket_name: "bucket"
  public_bucket_url: "https://pub-e7ae7f4305084b3ea6e32696f803a332.r2.dev/"
  
image:
  original_image_path: "original/"
  processed_image_path: "processed/"


post:
  recent_comments_count: 2


