// Code generated by hertz generator.

package main

import (
	handler "bandlab_feed_server/biz/handler"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func register(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

}
